version: "2"
checks:
  argument-count:
    enabled: true
  file-lines:
    enabled: true
engines:
  rubocop:
    enabled: false
  eslint:
    enabled: true
ratings:
  paths:
    - "**.js"
    - "**.jsx"
